// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/477643b46bc24e9b76420ac658e87e1ff2b1f197/koa-mount/koa-mount.d.ts
declare module "koa-mount" {

    import * as Koa from "koa";

    interface Function { (ctx: Koa.Context, next?: () => any): any }

    function mount(app: Function): Function;

    function mount(app: Koa): Function;

    function mount(prefix: string, app: Function): Function;

    function mount(prefix: string, app: Koa): Function;

    namespace mount {}
    export = mount;
}